In [6]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.3.5
2.3.3

In [9]:
ex = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")
ex

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90
...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83

In [11]:
ex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [12]:
ex.shape

(1000, 12)

In [ ]:
ex.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [14]:
ex.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [16]:
ex.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [17]:
print(ex.head())
print(ex.shape)
print(ex.columns)
print(ex.info())

    Order_ID  Order_Date Customer_ID Customer_Name   Age  Gender       City  \
0  ORD100002  2025-02-25    CUST5529  Customer_227  30.0  Female  Bengaluru
1  ORD100003  2025-10-14    CUST3127  Customer_182  63.0    Male  Bengaluru
2  ORD100004  2025-05-13    CUST8887  Customer_487  62.0  Female  Bengaluru
3  ORD100005  2025-12-02    CUST2515  Customer_470  65.0  Female    Kolkata
4  ORD100006  2025-11-20    CUST4796  Customer_380  44.0    Male  Bengaluru

  Product     Category  Quantity  Unit_Price  Total_Sales
0    Rice      Grocery         7     2829.77     19808.39
1    Book    Education         5    27906.16    139530.80
2    Book    Education         8    37491.06    299928.48
3  Mobile  Electronics         9    28541.36    256872.24
4    Rice      Grocery        10    14036.59    140365.90
(1000, 12)
Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB
None

In [22]:
print("Dataset Shape:", ex.shape)
print("Total Rows:", len(ex))
print("Total Columns:", len(ex.columns))

Dataset Shape: (1000, 12)
Total Rows: 1000
Total Columns: 12

In [18]:
data_dictionary = pd.DataFrame({
    "Column": [
        "Order_ID",
        "Order_Date",
        "Customer_ID",
        "Customer_Name",
        "Age",
        "Gender",
        "City",
        "Product",
        "Category",
        "Quantity",
        "Unit_Price",
        "Total_Sales"
    ],
    "Data_Type": [
        "String",
        "Date",
        "String",
        "String",
        "Float",
        "String",
        "String",
        "String",
        "String",
        "Integer",
        "Float",
        "Float"
    ],
    "Description": [
        "Unique order identifier",
        "Date of order",
        "Unique customer identifier",
        "Name of customer",
        "Age of customer",
        "Gender of customer",
        "Customer city",
        "Purchased product",
        "Product category",
        "Number of items purchased",
        "Price per unit",
        "Total sales amount"
    ],
    "Business_Relevance": [
        "Track individual orders",
        "Analyze sales over time",
        "Identify customers",
        "Understand customer base",
        "Analyze customer demographics",
        "Gender-based sales analysis",
        "City-wise sales analysis",
        "Product performance",
        "Category-wise sales analysis",
        "Measure product demand",
        "Pricing analysis",
        "Revenue analysis"
    ]
})

data_dictionary

,Column,Data_Type,Description,Business_Relevance
0,Order_ID,String,Unique order identifier,Track individual orders
1,Order_Date,Date,Date of order,Analyze sales over time
2,Customer_ID,String,Unique customer identifier,Identify customers
3,Customer_Name,String,Name of customer,Understand customer base
4,Age,Float,Age of customer,Analyze customer demographics
5,Gender,String,Gender of customer,Gender-based sales analysis
6,City,String,Customer city,City-wise sales analysis
7,Product,String,Purchased product,Product performance
8,Category,String,Product category,Category-wise sales analysis
9,Quantity,Integer,Number of items purchased,Measure product demand
10,Unit_Price,Float,Price per unit,Pricing analysis
11,Total_Sales,Float,Total sales amount,Revenue analysis

In [ ]:
data_dictionary.to_excel(
    "data_dictionary.xlsx",index = False           # isko dictionary ko excel file me save karne ke liye
)

In [25]:
ex.isnull()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,True,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
ex.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [29]:
ex.duplicated().sum()

np.int64(0)

In [30]:
ex.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [31]:
ex.nunique()

Order_ID          992
Order_Date        342
Customer_ID       947
Customer_Name     425
Age                48
Gender              2
City                8
Product             6
Category            5
Quantity           10
Unit_Price       1000
Total_Sales      1000
dtype: int64

In [32]:
# 1. Missing Values
print("Missing Values:")
print(ex.isnull().sum())

# 2. Duplicate Records
print("\nDuplicate Records:")
print(ex.duplicated().sum())

# 3. Data Types
print("\nData Types:")
print(ex.dtypes)

# 4. Statistical Summary
print("\nStatistical Summary:")
print(ex.describe())

# 5. Unique Values
print("\nUnique Values:")
print(ex.nunique())

Missing Values:
Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

Duplicate Records:
0

Data Types:
Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

Statistical Summary:
              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

Unique Values:
Order_ID          992
Order_Date        342
Customer_ID       947
Customer_Name     425
Age                48
Gender              2
City                8
Product             6
Category            5
Quantity           10
Unit_Price       1000
Total_Sales      1000
dtype: int64

In [33]:
print(ex[ex["Age"].isnull()]) # Age ki record me kitni khali hai

      Order_ID  Order_Date Customer_ID Customer_Name  Age  Gender       City  \
48   ORD100050  2025-10-03    CUST5523  Customer_432  NaN    Male       Pune
98   ORD100100  2025-11-02    CUST7462  Customer_379  NaN    Male      Patna
148  ORD100150  2025-04-01    CUST4132   Customer_47  NaN  Female        NaN
198  ORD100200  2025-02-24    CUST2953  Customer_435  NaN  Female    Kolkata
248  ORD100250  2025-12-20    CUST3169  Customer_138  NaN  Female      Delhi
298  ORD100300  2025-07-01    CUST7944  Customer_282  NaN    Male        NaN
348  ORD100350  2025-07-11    CUST9709  Customer_409  NaN    Male       Pune
398  ORD100400  2025-04-20    CUST5102  Customer_416  NaN  Female  Hyderabad
448  ORD100450  2025-02-13    CUST6714   Customer_31  NaN  Female        NaN
498  ORD100500  2025-06-26    CUST2835  Customer_468  NaN    Male    Kolkata
548  ORD100550  2025-03-27    CUST5244   Customer_44  NaN    Male       Pune
598  ORD100050  2025-02-21    CUST8859   Customer_53  NaN    Male        NaN
648  ORD100650  2025-09-22    CUST2181  Customer_125  NaN  Female  Bengaluru
698  ORD100700  2025-05-20    CUST9674  Customer_232  NaN  Female     Mumbai
748  ORD100750  2025-07-18    CUST3730  Customer_273  NaN  Female        NaN
798  ORD100800  2025-09-27    CUST1618  Customer_166  NaN    Male      Patna
848  ORD100850  2025-04-12    CUST2834   Customer_98  NaN    Male    Kolkata
898  ORD100900  2025-04-27    CUST3867   Customer_54  NaN  Female        NaN
948  ORD100950  2025-11-01    CUST6316   Customer_59  NaN    Male       Pune
998  ORD101000  2025-02-21    CUST9501  Customer_241  NaN    Male      Delhi

    Product     Category  Quantity  Unit_Price  Total_Sales
48    Chair    Furniture         9    30834.87    277513.83
98   Laptop  Electronics         5      553.62      2768.10
148   Chair    Furniture         4     1973.64      7894.56
198    Rice      Grocery         8    27608.55    220868.40
248  Mobile  Electronics         7    19829.73    138808.11
298   Chair    Furniture         6    28595.31    171571.86
348  Laptop  Electronics         8    47254.70    378037.60
398    Book    Education         3    26269.62     78808.86
448    Book    Education        10    43946.96    439469.60
498   Chair    Furniture         9     7268.14     65413.26
548    Rice      Grocery         5    41509.54    207547.70
598  Laptop  Electronics         7    20144.84    141013.88
648    Rice      Grocery         3     7467.04     22401.12
698  Mobile  Electronics         9    11808.33    106274.97
748   Chair    Furniture        10    43808.06    438080.60
798    Rice      Grocery        10    15891.66    158916.60
848    Rice      Grocery         9    30091.26    270821.34
898  Laptop  Electronics         5     5069.79     25348.95
948  Laptop  Electronics         9    34569.56    311126.04
998  Mobile  Electronics         9     2879.01     25911.09

In [34]:
print(ex[ex["City"].isnull()]) # City me khali record

      Order_ID  Order_Date Customer_ID Customer_Name   Age  Gender City  \
73   ORD100075  2025-03-30    CUST2157   Customer_31  58.0    Male  NaN
148  ORD100150  2025-04-01    CUST4132   Customer_47   NaN  Female  NaN
223  ORD100225  2025-12-07    CUST1443  Customer_315  37.0  Female  NaN
298  ORD100300  2025-07-01    CUST7944  Customer_282   NaN    Male  NaN
373  ORD100375  2025-05-06    CUST5835  Customer_362  20.0    Male  NaN
448  ORD100450  2025-02-13    CUST6714   Customer_31   NaN  Female  NaN
523  ORD100525  2025-12-31    CUST1090  Customer_316  45.0  Female  NaN
598  ORD100050  2025-02-21    CUST8859   Customer_53   NaN    Male  NaN
673  ORD100675  2025-11-20    CUST8502  Customer_220  47.0    Male  NaN
748  ORD100750  2025-07-18    CUST3730  Customer_273   NaN  Female  NaN
823  ORD100825  2025-07-13    CUST9718   Customer_11  57.0  Female  NaN
898  ORD100900  2025-04-27    CUST3867   Customer_54   NaN  Female  NaN
973  ORD100975  2025-10-15    CUST2870  Customer_311  25.0  Female  NaN

    Product     Category  Quantity  Unit_Price  Total_Sales
73   Mobile  Electronics         4    21599.26     86397.04
148   Chair    Furniture         4     1973.64      7894.56
223    Rice      Grocery         1    25336.70     25336.70
298   Chair    Furniture         6    28595.31    171571.86
373  Laptop  Electronics         2    28311.58     56623.16
448    Book    Education        10    43946.96    439469.60
523   Shoes      Fashion         7      751.97      5263.79
598  Laptop  Electronics         7    20144.84    141013.88
673  Laptop  Electronics         1    14756.18     14756.18
748   Chair    Furniture        10    43808.06    438080.60
823  Laptop  Electronics         2    45863.13     91726.26
898  Laptop  Electronics         5     5069.79     25348.95
973    Book    Education         6     6189.16     37134.96

In [35]:
# जिन Order_ID की पुनरावृत्ति हुई है
duplicate_ids = ex[
    ex["Order_ID"].duplicated(keep=False)
]

print(duplicate_ids.sort_values("Order_ID"))

      Order_ID  Order_Date Customer_ID Customer_Name   Age  Gender       City  \
48   ORD100050  2025-10-03    CUST5523  Customer_432   NaN    Male       Pune
118  ORD100050  2025-01-22    CUST3194  Customer_114  34.0    Male    Kolkata
238  ORD100050  2025-03-01    CUST8467  Customer_104  23.0    Male  Bengaluru
358  ORD100050  2025-02-11    CUST6467  Customer_181  24.0  Female       Pune
478  ORD100050  2025-11-22    CUST8225  Customer_468  64.0    Male  Bengaluru
598  ORD100050  2025-02-21    CUST8859   Customer_53   NaN    Male        NaN
718  ORD100050  2025-11-06    CUST7824  Customer_190  31.0  Female     Mumbai
838  ORD100050  2025-08-03    CUST5585  Customer_289  35.0    Male    Kolkata
958  ORD100050  2025-02-09    CUST7188   Customer_89  62.0    Male  Bengaluru

    Product     Category  Quantity  Unit_Price  Total_Sales
48    Chair    Furniture         9    30834.87    277513.83
118    Book    Education         2    25795.55     51591.10
238    Book    Education         3     2860.83      8582.49
358    Rice      Grocery         7    45480.39    318362.73
478    Rice      Grocery         8    38957.59    311660.72
598  Laptop  Electronics         7    20144.84    141013.88
718    Rice      Grocery         4    42642.59    170570.36
838   Chair    Furniture         9    28747.47    258727.23
958  Mobile  Electronics         1    34619.77     34619.77

In [36]:
print("Duplicate Order IDs:",
      ex["Order_ID"].duplicated().sum())

print("Unique Order IDs:",
      ex["Order_ID"].nunique())

Duplicate Order IDs: 8
Unique Order IDs: 992

In [37]:
# हर Order_ID कितनी बार आया है
print(
    ex["Order_ID"].value_counts()
    .loc[lambda x: x > 1]
)

Order_ID
ORD100050    9
Name: count, dtype: int64

In [38]:
# ORD100050 के सभी रिकॉर्ड देखना
ex[ex["Order_ID"] == "ORD100050"]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

In [39]:
# Duplicate Order IDs की जाँच
duplicate_check = (
    ex.groupby("Order_ID")
    .agg(
        Total_Records=("Order_ID", "size"),
        Unique_Customers=("Customer_ID", "nunique"),
        Unique_Dates=("Order_Date", "nunique"),
        Unique_Products=("Product", "nunique")
    )
    .query("Total_Records > 1")
)

print(duplicate_check)

           Total_Records  Unique_Customers  Unique_Dates  Unique_Products
Order_ID
ORD100050              9                 9             9                5

In [41]:
# Duplicate Order IDs को Flag करना
ex["Duplicate_Order_ID"] = ex[
    "Order_ID"
].duplicated(keep=False)

# केवल Duplicate IDs वाले रिकॉर्ड देखना
duplicate_records = ex[
    ex["Duplicate_Order_ID"]
]

print(duplicate_records[
    ["Order_ID", "Customer_ID", "Order_Date",
     "Product", "Duplicate_Order_ID"]
])

      Order_ID Customer_ID  Order_Date Product  Duplicate_Order_ID
48   ORD100050    CUST5523  2025-10-03   Chair                True
118  ORD100050    CUST3194  2025-01-22    Book                True
238  ORD100050    CUST8467  2025-03-01    Book                True
358  ORD100050    CUST6467  2025-02-11    Rice                True
478  ORD100050    CUST8225  2025-11-22    Rice                True
598  ORD100050    CUST8859  2025-02-21  Laptop                True
718  ORD100050    CUST7824  2025-11-06    Rice                True
838  ORD100050    CUST5585  2025-08-03   Chair                True
958  ORD100050    CUST7188  2025-02-09  Mobile                True

In [42]:
# Missing Values की प्रतिशत जाँच
missing_percentage = (
    ex.isnull().sum() / len(ex) * 100
).round(2)

print(missing_percentage[
    missing_percentage > 0
])

Age     2.0
City    1.3
dtype: float64

In [43]:
# Age की Median निकालना
age_median = ex["Age"].median()

print("Age Median:", age_median)

# Missing Age को Median से भरना
ex["Age"] = ex["Age"].fillna(age_median)

Age Median: 41.0

In [44]:
# Missing City को Unknown से भरना
ex["City"] = ex["City"].fillna("Unknown")

In [45]:
# दोबारा Missing Values चेक करना
print(ex.isnull().sum())

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Age                   0
Gender                0
City                  0
Product               0
Category              0
Quantity              0
Unit_Price            0
Total_Sales           0
Duplicate_Order_ID    0
dtype: int64

In [47]:
# सभी Columns के Data Types
print(ex.dtypes)

# Order_Date का Data Type
print("\nOrder_Date Type:")
print(ex["Order_Date"].dtype)

Order_ID               object
Order_Date             object
Customer_ID            object
Customer_Name          object
Age                   float64
Gender                 object
City                   object
Product                object
Category               object
Quantity                int64
Unit_Price            float64
Total_Sales           float64
Duplicate_Order_ID       bool
dtype: object

Order_Date Type:
object

In [48]:
ex["Order_Date"] = pd.to_datetime(
    ex["Order_Date"],
    errors="coerce"
)

In [49]:
print(ex["Order_Date"].dtype)
print(ex["Order_Date"].isnull().sum())

datetime64[ns]
0

In [50]:
# Convert Order_Date into datetime format

ex["Order_Date"] = pd.to_datetime(
    ex["Order_Date"],
    errors="coerce"
)

# Check the data type
print(ex["Order_Date"].dtype)

datetime64[ns]

In [51]:
# Check invalid dates
print("Invalid Dates:",
      ex["Order_Date"].isnull().sum())

# Check date range
print("Minimum Date:",
      ex["Order_Date"].min())

print("Maximum Date:",
      ex["Order_Date"].max())

Invalid Dates: 0
Minimum Date: 2025-01-01 00:00:00
Maximum Date: 2026-01-01 00:00:00

In [52]:
ex["Age"] = ex["Age"].astype("Int64")

print(ex["Age"].dtype)

Int64

In [53]:
# Calculate expected sales
ex["Calculated_Sales"] = (
    ex["Quantity"] * ex["Unit_Price"]
).round(2)

# Compare with actual sales
ex["Sales_Mismatch"] = (
    (ex["Total_Sales"] - ex["Calculated_Sales"]).abs() > 0.01
)

print("Sales Mismatch:")
print(ex["Sales_Mismatch"].sum())

Sales Mismatch:
0

In [55]:
# Extract year, month and day
ex["Order_Year"] = ex["Order_Date"].dt.year
ex["Order_Month"] = ex["Order_Date"].dt.month
ex["Order_Day"] = ex["Order_Date"].dt.day

# Categorize customers by age
ex["Age_Group"] = pd.cut(
    ex["Age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle_Aged", "Senior"]
)

# Calculate total sales independently
ex["Calculated_Sales"] = (
    ex["Quantity"] * ex["Unit_Price"]
).round(2)


# Display newly created columns
ex[[
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Order_Day",
    "Age",
    "Age_Group",
    "Quantity",
    "Unit_Price",
    "Calculated_Sales"
]].head(10)

,Order_Date,Order_Year,Order_Month,Order_Day,Age,Age_Group,Quantity,Unit_Price,Calculated_Sales
0,2025-02-25,2025,2,25,30,Adult,7,2829.77,19808.39
1,2025-10-14,2025,10,14,63,Senior,5,27906.16,139530.80
2,2025-05-13,2025,5,13,62,Senior,8,37491.06,299928.48
3,2025-12-02,2025,12,2,65,Senior,9,28541.36,256872.24
4,2025-11-20,2025,11,20,44,Middle_Aged,10,14036.59,140365.90
5,2025-12-31,2025,12,31,40,Adult,9,35947.47,323527.23
6,2025-10-14,2025,10,14,61,Senior,6,49997.53,299985.18
7,2025-12-05,2025,12,5,35,Adult,3,9488.83,28466.49
8,2025-11-21,2025,11,21,41,Middle_Aged,6,19488.23,116929.38
9,2025-04-16,2025,4,16,30,Adult,8,18024.34,144194.72

In [56]:
print("New Columns:")
print(ex.columns.tolist())

print("\nDataset Shape:")
print(ex.shape)

print("\nAge Group Counts:")
print(ex["Age_Group"].value_counts())

New Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales', 'Duplicate_Order_ID', 'Calculated_Sales', 'Sales_Mismatch', 'Order_Year', 'Order_Month', 'Order_Day', 'Age_Group']

Dataset Shape:
(1000, 19)

Age Group Counts:
Age_Group
Middle_Aged    411
Adult          326
Young          158
Senior         105
Name: count, dtype: int64

In [57]:
# Outlier detection using IQR
columns = ["Age", "Quantity", "Unit_Price", "Total_Sales"]

for col in columns:
    Q1 = ex[col].quantile(0.25)
    Q3 = ex[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ex[
        (ex[col] < lower) | (ex[col] > upper)
    ]

    print(f"\n{col}")
    print("Lower Limit:", round(lower, 2))
    print("Upper Limit:", round(upper, 2))
    print("Outliers:", len(outliers))

Age
Lower Limit: -4.5
Upper Limit: 87.5
Outliers: 0

Quantity
Lower Limit: -4.5
Upper Limit: 15.5
Outliers: 0

Unit_Price
Lower Limit: -21529.27
Upper Limit: 72937.37
Outliers: 0

Total_Sales
Lower Limit: -187917.74
Upper Limit: 438707.26
Outliers: 19

In [59]:
# Find Total_Sales outliers
Q1 = ex["Total_Sales"].quantile(0.25)
Q3 = ex["Total_Sales"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Filter outliers
sales_outliers = ex[
    (ex["Total_Sales"] < lower) |
    (ex["Total_Sales"] > upper)
]

# Display outlier records
print("Total Outliers:", len(sales_outliers))

sales_outliers[[
    "Order_ID",
    "Customer_ID",
    "Product",
    "Category",
    "Quantity",
    "Unit_Price",
    "Total_Sales"
]].sort_values("Total_Sales", ascending=False)

Total Outliers: 19

,Order_ID,Customer_ID,Product,Category,Quantity,Unit_Price,Total_Sales
50,ORD100052,CUST2062,Book,Education,10,49367.75,493677.50
762,ORD100764,CUST4706,Laptop,Electronics,10,49217.41,492174.10
220,ORD100222,CUST1711,Shoes,Fashion,10,49086.64,490866.40
972,ORD100974,CUST4869,Laptop,Electronics,10,48566.78,485667.80
622,ORD100624,CUST7416,Rice,Grocery,10,48255.19,482551.90
364,ORD100366,CUST9551,Mobile,Electronics,10,47493.59,474935.90
947,ORD100949,CUST8381,Book,Education,10,47314.42,473144.20
712,ORD100714,CUST4037,Mobile,Electronics,10,47079.86,470798.60
980,ORD100982,CUST4003,Rice,Grocery,10,46852.20,468522.00
656,ORD100658,CUST4584,Shoes,Fashion,10,46270.13,462701.30
691,ORD100693,CUST4270,Book,Education,10,45877.49,458774.90
173,ORD100175,CUST3564,Rice,Grocery,9,49390.42,444513.78
721,ORD100723,CUST8657,Laptop,Electronics,10,44401.64,444016.40
462,ORD100464,CUST1710,Book,Education,10,44045.66,440456.60
432,ORD100434,CUST4982,Mobile,Electronics,10,43997.22,439972.20
81,ORD100083,CUST8346,Laptop,Electronics,9,48845.50,439609.50
150,ORD100152,CUST5188,Laptop,Electronics,9,48833.27,439499.43
448,ORD100450,CUST6714,Book,Education,10,43946.96,439469.60
396,ORD100398,CUST6600,Mobile,Electronics,9,48807.37,439266.33

In [61]:
# Flag potential sales outliers
Q1 = ex["Total_Sales"].quantile(0.25)
Q3 = ex["Total_Sales"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

ex["Sales_Outlier"] = (
    (ex["Total_Sales"] < lower) |
    (ex["Total_Sales"] > upper)
)

# Check the result
print(ex["Sales_Outlier"].value_counts())

Sales_Outlier
False    981
True      19
Name: count, dtype: int64

In [62]:
# Final validation
print("Dataset Shape:", ex.shape)

print("\nMissing Values:")
print(ex.isnull().sum().sum())

print("\nExact Duplicate Rows:")
print(ex.duplicated().sum())

print("\nSales Mismatch:")
print(ex["Sales_Mismatch"].sum())

print("\nSales Outliers:")
print(ex["Sales_Outlier"].sum())

print("\nDuplicate Order ID Rows:")
print(ex["Duplicate_Order_ID"].sum())

Dataset Shape: (1000, 20)

Missing Values:
0

Exact Duplicate Rows:
0

Sales Mismatch:
0

Sales Outliers:
19

Duplicate Order ID Rows:
9

In [63]:
# Remove temporary validation columns
df_final = ex.drop(
    columns=[
        "Calculated_Sales",
        "Sales_Mismatch"
    ],
    errors="ignore"
)

# Save final cleaned dataset
df_final.to_csv(
    "cleaned_sales.csv",
    index=False
)

print("Cleaned dataset saved successfully!")
print("Final Shape:", df_final.shape)

Cleaned dataset saved successfully!
Final Shape: (1000, 18)